name: lbp3b_windows
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2023.01.10
  - libffi=3.2.1
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.0
  - setuptools=66.0.0
  - sqlite=3.33.0
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - anndata==0.9.1
      - anyio==3.6.2
      - app-model==0.1.4
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asciitree==0.3.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - bokeh==3.1.0
      - build==0.10.0
      - cachey==0.2.1
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cloudpickle==2.2.1
      - comm==0.1.3
      - contourpy==1.0.7
      - csbdeep==0.7.3
      - cycler==0.11.0
      - cython==0.29.34
      - dask==2023.4.0
      - dask-image==2023.3.0
      - debugpy==1.6.7
      - decorator==4.4.2
      - defusedxml==0.7.1
      - distributed==2023.4.0
      - docstring-parser==0.15
      - docutils==0.17.1
      - entrypoints==0.4
      - executing==1.2.0
      - fasteners==0.18
      - fastjsonschema==2.16.3
      - fastremap==1.13.4
      - fonttools==4.39.3
      - fqdn==1.5.1
      - freetype-py==2.3.0
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - h5py==3.8.0
      - hdbscan==0.8.29
      - heapdict==1.0.1
      - hsluv==5.0.3
      - idna==3.4
      - igraph==0.10.4
      - imagecodecs==2023.3.16
      - imagecodecs-lite==2022.9.26
      - imageio==2.28.0
      - imageio-ffmpeg==0.4.8
      - imagesize==1.4.1
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - in-n-out==0.1.7
      - inflect==6.0.4
      - ipykernel==6.22.0
      - ipynbname==2023.1.0.0
      - ipython==8.12.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - leidenalg==0.9.1
      - llvmlite==0.38.1
      - locket==1.0.0
      - lz4==4.3.2
      - magicgui==0.7.2
      - mahotas==1.4.11
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==2.0.5
      - msgpack==1.0.5
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - napari==0.4.17
      - napari-console==0.0.8
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.6
      - natsort==8.3.1
      - nbclassic==0.5.5
      - nbclient==0.7.3
      - nbconvert==7.3.1
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==2.8.8
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - npe2==0.7.0
      - numba==0.55.2
      - numcodecs==0.11.0
      - numpy==1.22.4
      - numpydoc==1.5.0
      - omnipath==1.0.6
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - openpyxl==3.1.2
      - openslide-python==1.2.0
      - packaging==23.1
      - pandas==2.0.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.4.0
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pims==0.6.1
      - pint==0.20.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.2.0
      - pooch==1.7.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - psygnal==0.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==11.0.0
      - pycparser==2.21
      - pydantic==1.10.7
      - pygments==2.15.1
      - pynndescent==0.5.10
      - pyopengl==3.1.6
      - pyparsing==3.0.9
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytomlpp==1.0.13
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.1
      - qtpy==2.3.1
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.4
      - scanpy==1.9.3
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - seaborn==0.12.2
      - send2trash==1.8.0
      - six==1.16.0
      - slicerator==1.1.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - squidpy==1.2.3
      - stack-data==0.6.2
      - stardist==0.8.3
      - statsmodels==0.13.5
      - superqt==0.4.1
      - tblib==1.7.0
      - terminado==0.17.1
      - texttable==1.6.7
      - tifffile==2023.4.12
      - tinycss2==1.2.1
      - tomli==2.0.1
      - toolz==0.12.0
      - tornado==6.3.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typer==0.7.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==1.26.15
      - validators==0.20.0
      - vispy==0.11.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - widgetsnbextension==4.0.7
      - wrapt==1.15.0
      - xarray==2023.1.0
      - xyzservices==2023.2.0
      - yarl==1.9.1
      - zarr==2.14.2
      - zict==3.0.0
      - zipp==3.15.0
prefix: /nfs/users/nfs_b/bw17/.conda/envs/lbp3b
